services:

  reverse-proxy:
    image: traefik:v2.11
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

    frontend:
      image: nginx:latest
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`front.quantum.local`)"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"

    backend:
      image: nginx:latest
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`back.quantum.local`)"
        - "traefik.http.services.backend.loadbalancer.server.port=80"
