---
#https://docs.ansible.com/ansible/latest/collections/community/docker/docker_swarm_module.html
#https://docs.docker.com/engine/swarm/swarm-mode/

- name: Check if Docker Swarm is already initialized if else not initialized swarm
  shell: docker info
  register: swarm_info
  when: "'manager' in inventory_hostname"

- name: Initialize Docker Swarm
  command: docker swarm init --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
  args:
    creates: /etc/docker/daemon.json
  ignore_errors: true
  register: swarm_init_result
  run_once: true
  changed_when: "'This node is a manager' not in swarm_info.stdout and 'Swarm: inactive' in swarm_init_result.stdout"
  when: "'manager' in inventory_hostname and 'Swarm: inactive' in swarm_info.stdout"

- name: Retrieve join token for workers
  command: docker swarm join-token worker -q
  register: join_token
  when: "'manager' in inventory_hostname and swarm_info.stdout is defined and 'This node is a manager' in swarm_info.stdout"

- name: Retrieve join token for managers
  command: docker swarm join-token manager -q
  register: manager_token
  when: "'manager' in inventory_hostname and swarm_info.stdout is defined and 'This node is a manager' in swarm_info.stdout"

- name: Set Docker Swarm join token facts
  set_fact:
    docker_swarm_worker_token: "{{ join_token.stdout }}"
    docker_swarm_manager_token: "{{ manager_token.stdout }}"
  when: swarm_info is defined and swarm_info.stdout is defined and 'This node is a manager' in swarm_info.stdout