---
# Documentations
# https://docs.gitlab.com/runner/install/linux-repository.html
# https://gitlab.com/k33g_org/k33g_org.gitlab.io/-/issues/84
# https://adfinis.com/fr/blog/gitlab-ci/
# https://www.bejean.eu/2021/02/14/mettre-en-place-un-gitlab-runner

- name: Download Gitlab repository installer script
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: '0755'

- name: Run the Gitlab repository installer script
  command: bash /tmp/script.deb.sh

- name: Install gitlab-runner
  apt:
    name: gitlab-runner
    update_cache: yes
